<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZnaw4cd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZnaw4cd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZnaw4cd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZnaw4cd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZnaw4cd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Znaw4cd',
    'container.build_id' => '03a45c58',
    'container.build_time' => 1523435755,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZnaw4cd');
